---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-16.04
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: 2m/arch-pkgbuild-builder@v1.16
        with:
          target: 'pkgbuild'
          pkgname: 'zen-kernel'
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v0.0.2
        with:
          file_or_dir: .github/workflows/ci.yml
